# Generated by Django 3.0.5 on 2020-05-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfectextractor_ui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('path', models.FilePathField(allow_files=False, allow_folders=True, path='/media/bignux/', recursive=True)),
                ('is_public', models.BooleanField()),
                ('source_format', models.CharField(choices=[('opus', 'opus'), ('bnc', 'bnc'), ('dpc', 'dpc')], max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Corpora',
            },
        ),
    ]
